- XOR Profit Trick
- ACODE- Recursive Approach, Backtracking basics
- N Queen - all 3 approaches & Complexity analysis
- Permuation(T), Sudoku(T),Rat In a Maze(T)
- HW - MKJUMPS(Spoj), Knights Move(GFG)
- Binary Search(Divide & Conquer)
